ITEM.name = "Machete"
ITEM.description = "A heavily rusted machete."
ITEM.model = "models/weapons/w_machete.mdl"
ITEM.class = "weapon_machete"
ITEM.weaponCategory = "melee"
ITEM.flag = "v"
ITEM.width = 2
ITEM.height = 1
ITEM.weight = 3