--This is for HL2RP. Delete at your own discretion. I'm leaving it in since all it does is take up a kilobyte or so of space.
ix.anim.SetModelClass("models/humans/group01/male_01.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_02.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_04.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_05.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_06.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_07.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_08.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_09.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group02/male_01.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group02/male_03.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group02/male_05.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group02/male_07.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group02/male_09.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_40.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_41.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_38.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_67.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_75.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_86.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_96.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_hc.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_93.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_83.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_117.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_122.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_120.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_115.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_110.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_111.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_12.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_51.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_65.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_63.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_50.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_49.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_62.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_70.mdl", "citizen_male")
ix.anim.SetModelClass("models/humans/group01/male_45.mdl", "citizen_male")
ix.anim.SetModelClass("models/bloo_ltcom/citizens/male_10.mdl", "citizen_male")
ix.anim.SetModelClass("models/bloo_ltcom/citizens/male_11.mdl", "citizen_male")
ix.anim.SetModelClass("models/barnes/refugee/female_31.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_32.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_34.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_41.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_42.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_caterina.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_01.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_02.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_03.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_06.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_07.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group02/female_01.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group02/female_03.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group02/female_06.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_04.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/citizen/female_01.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/citizen/female_02.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_05.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_40.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_38.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_28.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/citizen/female_03.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/citizen/female_04.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/citizen/female_06.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/citizen/female_07.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_67.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_28.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_03.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_06.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_07.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_04.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_43.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_25.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_29.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_43.mdl", "citizen_female")
ix.anim.SetModelClass("models/barnes/refugee/female_44.mdl", "citizen_female")
ix.anim.SetModelClass("models/humans/group01/female_78.mdl", "citizen_female")
ix.anim.SetModelClass("models/dpfilms/metropolice/arctic_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/biopolice.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/blacop.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/c08cop.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/civil_medic.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/elite_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/female_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/hdpolice.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/hl2beta_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/hl2concept.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/hunter_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/phoenix_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/police_bt.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/police_fragger.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/policetrench.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/resistance_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/retrocop.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/rogue_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/rtb_police.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/urban_police.mdl", "metrocop")
ix.anim.SetModelClass("models/auditor/custom/combine2019/chr_combine_soldier_hazmat.mdl", "overwatch")
ix.anim.SetModelClass("models/auditor/custom/combine2019/chr_combine_soldier_light.mdl", "overwatch")
ix.anim.SetModelClass("models/auditor/custom/combine2019/chr_combine_soldier_light_elite.mdl", "overwatch")
ix.anim.SetModelClass("models/auditor/custom/combine2019/chr_combine_soldier_patrol_vest.mdl", "overwatch")
ix.anim.SetModelClass("models/ninja/combine/combine_soldier.mdl", "overwatch")
ix.anim.SetModelClass("models/ninja/combine/combine_super_soldier.mdl", "overwatch")
ix.anim.SetModelClass("models/ninja/combine/combinonew_armor.mdl", "overwatch")
ix.anim.SetModelClass("models/wichacks/sandro.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/ted.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/vance.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/van.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/eric.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/erdim.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/art.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/joe.mdl", "citizen_male")
ix.anim.SetModelClass("models/wichacks/mike.mdl", "citizen_male")
ix.anim.SetModelClass("models/cultist/hl_a/vannila_combine/npc/combine_soldier.mdl", "overwatch")
ix.anim.SetModelClass("models/industrial_uniforms/industrial_uniform2.mdl", "citizen_male")
ix.anim.SetModelClass("models/industrial_uniforms/industrial_uniform.mdl", "citizen_male")
ix.anim.SetModelClass("models/cultist/hl_a/combine_commander/combine_commander.mdl", "overwatch")
ix.anim.SetModelClass("models/city8_ow_elite.mdl", "overwatch")
ix.anim.SetModelClass("models/city8_overwatch.mdl", "overwatch")
ix.anim.SetModelClass("models/city8_overwatch_elite.mdl", "overwatch")
ix.anim.SetModelClass("models/eliteshockcp.mdl", "metrocop")
ix.anim.SetModelClass("models/vortigaunt_ozaxi.mdl", "vortigaunt")
ix.anim.SetModelClass("models/c08cop_someguy.mdl", "metrocop")
ix.anim.SetModelClass("models/dpfilms/metropolice/playermodels/pm_zombie_police.mdl", "zombie")

--Here are the Metro Models used. If you wanna add some, go ahead.
ix.anim.SetModelClass("models/ninja/signalvariance/act_middle_revolyucioner2_a3.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_middle_revolyucioner2_artyom.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_middle_revolyucioner2_hunter.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_banzay_hunter.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_banzay_rus_soldier_a3.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_banzay_rus_soldier_bf4.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_banzay_rus_soldier_hunter.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_bomj2_bf4.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_bomj2_hunter.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_2033_khan.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_34_pavel.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_middle_revolyucioner_a3.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_middle_revolyucioner_artyom.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_middle_revolyucioner_bf4.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_middle_revolyucioner_hunter.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_fedor_burbon_artyom.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_fedor_burbon_bf4.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_ganza_a3.mdl","citizen_male")
ix.anim.SetModelClass("models/ninja/signalvariance/act_ganza_artyom.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/hanza/hanza_soldier_1.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/hanza/hanza_soldier_2.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/hanza/hanza_soldier_3.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/hanza/hanza_soldier_4.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/hanza/hanza_soldier_5.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/hazmat.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/hazmat_2.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/hazmat_3.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/hazmat_4.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/medic.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/medic2.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/medicshapka.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/new_medic01.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/new_medic02.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/new_medic03.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/security_station_v1.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/security_station_v2.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/security_station_v3.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/security_station_v4.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/neutral/stalker.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_offcier_1.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_offcier_2.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_officer_3.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_officer_4.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_officer_5.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_officer_6.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_1.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_10.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_11.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_12.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_13.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_14.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_15.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_16.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_17.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_18.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_19.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_2.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_20.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_3.mdl","citizen_male")
ix.anim.SetModelClass("models/arx/redline/red_line_soldier_4.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit1.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit1_n.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit1_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit2_n.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit2_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit3.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit3_n.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit3_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit4.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit4_n.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit4_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit5.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit5_n.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit6.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit6_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit7_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit8_2_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bandit8_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/bourbon.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/civpilot.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_anna_summer.mdl","citizen_female")
ix.anim.SetModelClass("models/magma/exodus_damir.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_duke.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_idiot.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_katya.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_krest.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_lyosha.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_miller.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_miller_snow.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_sam.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_stepan.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/exodus_tokarev.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/hanzasoldier2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/hanzasoldier2_nosok.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/hanzasoldier_balaclava.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/hazmatsoldier.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/hazmatsoldier_face.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/hunter.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/leonid.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/officer_reich.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/pavel_original.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_heavy_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_flamethrower.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_kgb_lestnisky.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_kgb_soldier.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_kgb_soldier_mask.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_kgb_soldier_mask2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_patrolsoldier.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_privatesoldier.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_privatesoldier_face.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redline_soldier_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redlineofficer.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redlinesoldier.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redlinesoldier_nosok.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redlinesoldier_nosok_v2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/redlinesoldier_v2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_dieseldlc.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_general_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_hans.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_heavy_trooper.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_heavy_trooper_reinforcement.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_hood.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_hood2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_hookdlc.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_officer_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_othersoldier1.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_othersoldier1_black.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_othersoldier2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_othersoldier2_b.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_othersoldier3.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_patrolsold.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_shock_sniper.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_shock_trooper.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_trooper.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_trooper_1.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_trooper_2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reich_trooper_3.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reichsoldier.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reichsoldier_2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reichsoldier_n.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reichsoldier_n_v2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/reichsoldier_v2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/russoldier.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/russoldier_nosok.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/russoldier_nosok_v2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/russoldier_v2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/sparta_soldier_balaclava1.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/sparta_soldier_balaclava2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/sparta_soldier_balaclava4.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/sparta_soldier_balaclava5.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/spartan_blue_mod.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/spartan_danila.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/spartan_elite_ranger.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/spartan_heavy.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/spartan_new_face.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/stalker1.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/stalker1_balaclava.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/stalker2.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/stalker3.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/stalker_hazmat.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/stalker_hazmat_face.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/stalker_spartan_balaclava.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/suhoy.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/survivor2_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/survivor7_redux.mdl","citizen_male")
ix.anim.SetModelClass("models/magma/ulman.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/a1b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/a2b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/a3b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/a4b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/a5b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/f1b1.mdl","citizen_female")
ix.anim.SetModelClass("models/half-dead/metroll/f3b1.mdl","citizen_female")
ix.anim.SetModelClass("models/half-dead/metroll/f4b1.mdl","citizen_female")
ix.anim.SetModelClass("models/half-dead/metroll/f6b1.mdl","citizen_female")
ix.anim.SetModelClass("models/half-dead/metroll/f7b1.mdl","citizen_female")
ix.anim.SetModelClass("models/half-dead/metroll/m6b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/m7b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/m8b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/m9b1.mdl","citizen_male")
ix.anim.SetModelClass("models/half-dead/metroll/m5b1.mdl","citizen_male")
ix.anim.SetModelClass("models/exodus/spartan/anna_chemsuit.mdl","citizen_male")
ix.anim.SetModelClass("models/devcon/mrp/act/longlostblake.mdl","citizen_male")